# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8fbfbcf23ae27d8ffdafe129a30a6158b664a2f0caa1a8ed437ff46d8f60b15813fc71e960625d6a0c665bbfbdcfafd788df8575ee69eafd12f327df22047c

test:
  secret_key_base: 861741c192fd9b0c7292c6bbd5ed125ce767968b1711d429f9b50be0bf9291a2fa5aae9ff41d6a6bbc91a8f2954ba5883c6fba1a8b262ccab0b4bc196108584d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
